name:                fileserve
version:             0.1.0.0
github:              "ncrashed/fileserve"
license:             BSD3
author:              "Anton Gushcha"
maintainer:          "ncrashed@gmail.com"
copyright:           "2017 Anton Gushcha"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/ncrashed/fileserve#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-server
    - wai
    - warp

executables:
  fileserve-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fileserve

tests:
  fileserve-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fileserve
